config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clinics
  root 'clinics#index'
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController

  before_action :find_clinics, only: [:show, :edit, :destroy, :update]

  def index
    @clinics = Clinic.all
  end

  def new
    @clinic = Clinic.new  
  end

  def show
  end

  def edit
  end

  def create
    @clinic = Clinic.new(clinic_params)
      if @clinic.save
        redirect_to clinic_path(clinic_params)
      else
        render 'new'
    end
  end

  def update
    if @clinic.update(clinic_params)
      redirect_to @clinic
    else
      render 'edit'
    end 
  end

  def destroy
    @clinic.destroy
    redirect_to clinics_path
  end
private

  def find_clinics
    @clinic = Clinic.find params[:id]
  end

  def clinic_params
    params.require(:clinic).permit(:clinic_name, :description, :address, :landline, :mobile, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.erb
<div class="container">
  <div class="form-custom"><%= form_for @clinic do |f| %>
  <div class="form-group">
    <%= f.label :clinic_name %>
    <%= f.text_field :clinic_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>  

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>  

  <div class="form-group">
    <%= f.label :landline %>
    <%= f.text_field :landline, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= f.label :mobile %>
    <%= f.text_field :mobile, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= f.label :monday %>
    <%= f.text_field :monday, class: "form-control" %>
  </div> 

    <div class="form-group">
    <%= f.label :tuesday %>
    <%= f.text_field :tuesday, class: "form-control" %>
  </div> 

    <div class="form-group">
    <%= f.label :wednesday %>
    <%= f.text_field :wednesday, class: "form-control" %>
  </div> 

    <div class="form-group">
    <%= f.label :thursday %>
    <%= f.text_field :thursday, class: "form-control" %>
  </div> 

    <div class="form-group">
    <%= f.label :friday %>
    <%= f.text_field :friday, class: "form-control" %>
  </div> 

    <div class="form-group">
    <%= f.label :saturday %>
    <%= f.text_field :saturday, class: "form-control" %>
  </div> 

    <div class="form-group">
    <%= f.label :sunday %>
    <%= f.text_field :sunday, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %> 
  </div>          
<% end %>
</div>
</div>

app/views/clinics/edit.html.erb
<%= render 'form' %>

app/views/clinics/index.html.erb
<div class="container">
      <div class="row index-heading">
        <div class="col-lg-8">
            <h1>Clinics<span class="glyphicon glyphicon-map-marker" style="color:#1abc9c"></span></h1>
          </div>
            <div class="col-lg-4">
          <% if user_signed_in? %>

          <div class="button-fix">
            <%= link_to 'Add Clinic', new_clinic_path, class: "btn btn-success" %>
          </div>

          <% end %>
          </div>
          </div>
        <hr>

          <div class="row">
              <% @clinics.each do |clinic| %> 
                  <div class="col-md-4 marketing places-index-img" >

                <h2><%= link_to clinic.clinic_name, clinic %></h2>

                <% if user_signed_in? && current_user.admin? %>
                <%= link_to 'Edit', edit_clinic_path(clinic), class: "btn btn-info" %>
                <%= link_to 'Destroy', clinic, method: :delete, class: "btn btn-danger" %>
                <% end %>
                </div>
              <% end %>
          </div>
  </div>
</div>

app/views/clinics/new.html.erb
<div class="container">
      <div class="row index-heading">
        <div class="col-lg-8">
            <h1>Add Clinics<span class="glyphicon glyphicon-map-marker" style="color:#1abc9c"></span></h1>
              <%= render 'form' %>
    </div>
  </div>
</div>

app/views/clinics/show.html.erb
<div class="container">
<%= @clinic.clinic_name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Relaxr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Navigation -->
  <div class="navbar navbar-default" role="navigation">
    <div class="container">

      <div class="navbar-header">
        <%= link_to root_path, class: "navbar-brand logo" do %>
         <a class="navbar-brand" href="#">Wellness United</a>
        <% end %>
      </div>

      <div class="collapse navbar-collapse">

        <div id="log_in_area" class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <span>
            <%= link_to edit_user_registration_path, class: "btn btn-info" do %>
            <span class="glyphicon glyphicon-edit"></span> Edit profile
            <% end %>  

            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-default" %>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-info" %> 

            <%= link_to new_user_session_path, class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-flash"></span> Login
            <% end %>  
          </span>
          <% end %>
        </div> 

        <ul class="nav navbar-nav navbar-left">

        </ul>

      </div>

    </div>
  </div>
  <!-- /Navigation -->



  <nav>
    <ul>
      <li><a href="#">Clinic search</a></li>
      <li><%= link_to 'Add Clinic', new_clinic_path %></li>
    </ul>
  </nav>

<%= yield %>


<script type="text/javascript" href="//cdnjs.cloudflare.com/ajax/libs/jQuery.mmenu/5.0.4/js/jquery.mmenu.min.js"></script>

<script type="text/javascript">
   $(document).ready(function() {
      $("#my-menu").mmenu();
   });
</script>
</body>
</html>